### ISSUE TITLE
All vDom based tests failing on IE11 with "Out of stack space" error

### ISSUE THREAD

**Issue by daffl** [canjs/can-vdom#10]
This seems to be more recent (I did not see it last week) but for some reason all (or most) vDom based tests in the full CanJS test suite are now failing with an `Out of stack space` error in IE11:

![screen shot 2016-10-31 at 3 35 00 pm](https://cloud.githubusercontent.com/assets/338316/19874071/dd2f9c0e-9f7f-11e6-967b-6e3409023100.png)

They are passing when run individually in their repositories. Related: https://github.com/canjs/canjs/pull/2627

**Comment by daffl** [comment]
Note: All tests are passing in IE9 and 10.

**Comment by daffl** [comment]
The only recent change related to this I published was https://github.com/canjs/can-view-target/pull/19. Thought I'd mention it although it doesn't look like it is causing the issue.

**Comment by matthewp** [comment]
I'm looking into it, I see the issue on my laptop.

**Comment by matthewp** [comment]
This is related to cloneNode, did something there change?

**Comment by daffl** [comment]
https://github.com/canjs/can-view-target/pull/20 causes other vDom errors that can be reproduced in Chrome as well by setting `clonesWork = true;` e.g. in https://github.com/canjs/can-view-target/blob/master/can-view-target.js#L62.

**Comment by matthewp** [comment]
This attribute copying doesn't work with vdom, change to:

``` js
var name = node.nodeName || node.name;
var value = node.nodeValue || node.value;
domAttr.setAttribute(copy, name, value);
```

nodeName and nodeValue are old properties, see https://developer.mozilla.org/en-US/docs/Web/API/Attr  I wouldn't remove them though, I'm not sure what the browser support is for `name` and `value`.
