### ISSUE TITLE
global.window doesn't contain everything on the global

### ISSUE THREAD

**Issue by matthewp** [canjs/can-vdom#2]
It is missing things like setTimeout. The reason is that it's a small object, only containing this stuff: https://github.com/canjs/can-vdom/blob/master/make-window/make-window.js

**Comment by matthewp** [comment]
The old way was to make the window === global.  Should we do that, or `assign(window, global())` @justinbmeyer ?

**Comment by matthewp** [comment]
I'm going to go with the first option for now.

**Comment by justinbmeyer** [comment]
is `setTimeout` enumerable on global?  I'm wondering if looping over everything and assigning it would work.

**Comment by matthewp** [comment]
Possibly, why do you like that method better?

**Comment by justinbmeyer** [comment]
I don't like it necessarily.  Just thinking through options.

**Comment by matthewp** [comment]
OK, I'm leaning towards what the PR does since we have to worry about enumerability
